### ISSUE TITLE
'Faster' difficulty replaces all difficulties

### ISSUE THREAD

**Issue by Sasurai087** [GrahamMThomas/RoR2_Faster-Games#5]
Hi Graham! Thanks for this mod, having a blast with it! Especially loving the ability to config the values. Can't wait to show my pals.
While playing around, I noticed the mod replaces all difficulties with blank icons (I'm aware that icons are still on your to-do). Is this intentional?

https://ibb.co/TP2PYkZ

This occurs even when enabled mods are: BepinEx{acl, R2API and FasterGames.

Thank you!

**Comment by GrahamMThomas** [comment]
Yeah, blank icons are intentional. After asking some experienced modders they made it sound like getting an image their would've been a nightmare, so I just left it blank.

In regards to replacing all difficulties. Currently I edit the characters model so even if you try to play on a different difficulty the models will still be changed. In order to prevent any confusion I just overwrote all difficulties so people realize they have to disable the mod if they want to play a different difficulty.
